### ISSUE TITLE
PackagedAuto support

### ISSUE THREAD

**Issue by phantamanta44** [phantamanta44/ae2-fluid-crafting#7]
allow unpackagers to emit fluids from fluid drops... somehow

**Comment by Exanthian** [comment]
I second this, with lots of large crafting batches going constantly I end up with hundreds of thousands of excess fluid drops that I can't use as fluid for some reason, they only exist in the system as fluid drops. Maybe have a fluid exporter for this mod that converts fluid drops into fluid upon export? That way you can set exports with fluid drops, and potentially have another actual fluid export to cover both bases. (Alternatively, somehow fix fluid drop build up, I don't know how it's happening as I'm importing the fluids themselves into my system, not drops. Maybe I'm just missing some functionality or interaction)

Love this mod, btw, this functionality has made my FTB Interactions playthrough 100x better as there are dozens and dozens of fluid crafting recipes.

Edit: I think what may be happening is I'm importing the fluids, the Discretizer is listing the drops as available, then I export the fluid, and the fluid is gone, but the drops remain in the system. Sorry I'm not very good at troubleshooting this as it's hard for me to pinpoint where the issue is happening.

**Comment by phantamanta44** [comment]
uhhhh that's not supposed to happen... on top of that, this issue is about packaged auto, not turning fluid drops into fluids arbitrarily; that's a non-goal and will not be implemented

**Comment by phantamanta44** [comment]
i suggest opening a new issue ticket and fully describing what's going on with examples and/or screenshots

**Comment by Exanthian** [comment]
Sorry to keep this issue off topic, I would definitely be willing to backtrack fully and see what's causing the buildup, but I'd also be interested in seeing if the Yefancy's dual interface might help before opening another issue. Is there a way to use the files here as a mod, or could these files be uploaded to CurseForge as a Jar? Sorry if those are stupid questions.

**Comment by phantamanta44** [comment]
you can build the mod by setting up a forge workspace and building it yourself. otherwise, I've just finished my last final exam, so I'll be getting back to working on this soon...

**Comment by Yefancy** [comment]
i have compiled a version for my own use before.
here's a compiled modified version if you need. https://github.com/Yefancy/ae2-fluid-crafting/releases
anyway, i recommend that you wait for Phantamamanta's next official release.

**Comment by Exanthian** [comment]
~~Very strange, droplet buildup is mitigated with Dual Interfaces instead of piping to tanks then fluid importing, but still there. Used to be every crafting operation would produce almost twice as much as it should in useless droplets, now it's only keeping a number of droplets in the system I can specify with a level emitter, but never crafts again because it never gets rid of the set amount of droplets still thinking they (The fluid) is still in the system. But this narrows things down, something must be funky with the level maintainer setup I'm using to maintain fluid levels in the system. I guess because I'm telling the system to keep fluid droplets in store / on autocraft but it can't differentiate between the real fluid and the droplets. Maybe level emitters aren't the way to go and I should just have dual interfaces with crafting upgrades requesting things on demand.~~ Level Maintainer doesn't play nice with this mod, think I got it figured out with regular AE2 level emitters, so sorry for all the fuss. Damn so much work trying to work around that when I should have just nixed it from the start ugh. EnderIO Dimensional Transcievers were also causing grief, taking them out before the level maintainer removed more droplet buildup but that could have also been linked back to the level maintainer. Hope your finals went well friend again sorry for the trouble. Also Yefancy's dual interface is killin' it both of you are amazing.

**Comment by phantamanta44** [comment]
i dunno why the level maintainer wouldn't work with fluids... could you open a new ticket describing the entire issue and your ae network setup?

**Comment by Exanthian** [comment]
Sure, I kinda had to take a lot of things apart and rework / isolate certain areas of my processing chains so I'll have to put some things back together but once It's all back in order I'll plug the level maintainer back in and try to help get to the bottom of these superfluous drops

**Comment by phantamanta44** [comment]
Implemented in 2f4ff15b3ffaaffd4eac1e6e6609b774f990f72f through 8c3876ed6dddd76780106def10b460a829c94e0d
